# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: demo-1
# spec:
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         app: demo-1-label
#     spec:
#       containers:
#         - name: demo-1-container
#           image: mgleon08/docker-demo:0.1.0
#           ports:
#             - containerPort: 3000
#   selector:
#     matchLabels:
#       app: demo-1-label

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{ include "demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 3000
  selector:
    matchLabels:
      {{- include "demo.selectorLabels" . | nindent 6 }}
