replicaCount: 2

image:
  repository: mgleon08/docker-demo
  tag: 0.2.0

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: ""
  hosts:
    - host: demo-2.com
      paths:
        - path: /
          pathType: Prefix
