apiVersion: v1
kind: Service # 元件屬性
metadata:
  name: demo-service # pod 名稱
spec:
  selector:
    app: demoApp
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001 # 通過 Service 暴露出來的一個Port, 可以在 Cluster 內進行訪問。
      targetPort: 3000 # Pod 和 Container 監聽的 Port。
      nodePort: 30390 # Cluster 向外網暴露出來的端口，可以讓外網能夠訪問到 Pod/Container。
